<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>golfcart_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the golf cart.</description>
  <maintainer email="dev@example.com">golfcart</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>golfcart_odrive</exec_depend>
  <exec_depend>golfcart_control</exec_depend>
  <exec_depend>golfcart_teleop</exec_depend>
  <exec_depend>golfcart_imu</exec_depend>
  <exec_depend>golfcart_gps</exec_depend>
  <exec_depend>golfcart_lidar</exec_depend>
  <exec_depend>golfcart_power</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
